name = "tradeagentiv"
main = "src/index.js"
compatibility_date = "2026-02-06"

#time
[triggers]
crons = [
  "*/30 * * * *",    # Price + Alerts
  "0 */4 * * *",     # Bundle: AI + F&G + Futures
  "0 9,15 * * *"     # Movers: 09:00 & 15:00 UTC
]
